name: weather-dl-v2-license-dep
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geojson
  - ecmwf-api-client=1.6.3
  - pip=22.3
  - pip:
    - kubernetes
    - google-cloud-logging
    - google-cloud-secret-manager
    - aiohttp
    - numpy
    - xarray
    - apache-beam[gcp]
    - firebase-admin
    - git+https://github.com/dabhicusp/cdsapi-beta-google-weather-tools.git@master#egg=cdsapi
