name: weather-tools
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cdsapi
  - ecmwf-api-client
  - apache-beam[gcp]
  - numpy
  - pandas
  - xarray
  - requests
  - google-cloud-firestore
  - dataclasses
  - cfgrib
  - netcdf4
  - geojson
  - more-itertools
  - simplejson
  - rioxarray
  - pyproj
  - gdal
  - scipy
  - pygrib
  - flake8
  - pytest
  - pytest-subtests
  - xarray-beam
  - absl-py
  - metview-batch
  - pip
  - pip:
    - firebase-admin
    - google-cloud-datastore
    - google-cloud-bigquery
    - urllib3==1.26.5
    - earthengine-api>=0.1.263
    - google-cloud-storage==2.2.1
    - pytype==2021.11.29