name: weather-tools
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cdsapi
  - ecmwf-api-client
  - apache-beam[gcp]
  - numpy
  - pandas
  - xarray
  - requests
  - google-cloud-firestore
  - dataclasses
  - cfgrib
  - netcdf4
  - geojson
  - simplejson
  - rioxarray
  - pyproj
  - gdal
  - pygrib
  - flake8
  - pytest
  - pytest-subtests
  - xarray-beam
  - absl-py
  - metview-batch
  - pip
  - pip:
    - firebase-admin